[package]
name = "graph-binary-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "1.0.0"
serde = {version = "1.0.136",features = ["derive"]}
thiserror = "1.0.30"