[package]
name = "graph-binary-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = {version = "1.1.0"}
serde = {version = "1.0.137",features = ["derive"]}
thiserror = "1.0.31"